/*
 * ebmMemDefs.h
 *
 *  Created on: 8 Sep 2019
 *      Author: tskoneskog
 */

#ifndef EBMMEMDEFS_H_
#define EBMMEMDEFS_H_

#define EBMMEMDEFS_VERSION 20240923

// ebmMemHandle type
#define MEM_TYPES		14			// no of MEM_TYPE_xxx
#define MEM_TYPE_STRING		1
#define MEM_TYPE_BIT		2
#define MEM_TYPE_UINT8		3
#define MEM_TYPE_INT8		4
#define MEM_TYPE_UINT16		5
#define MEM_TYPE_INT16		6
#define MEM_TYPE_UINT32		7
#define MEM_TYPE_INT32		8
#define MEM_TYPE_FLOAT		9
#define MEM_TYPE_DOUBLE		10
#define MEM_TYPE_UINT64		11
#define MEM_TYPE_UINTx3		12
#define MEM_TYPE_UINTx4		13
#define MEM_TYPE_UINTx5		14

// memtype FIFO, 0x100000 bit is set
#define MEM_TYPE_FIFO_STRING	33
#define MEM_TYPE_FIFO_BIT		34
#define MEM_TYPE_FIFO_UINT8		35
#define MEM_TYPE_FIFO_INT8		36
#define MEM_TYPE_FIFO_UINT16	37
#define MEM_TYPE_FIFO_INT16		38
#define MEM_TYPE_FIFO_UINT32	39
#define MEM_TYPE_FIFO_INT32		40
#define MEM_TYPE_FIFO_FLOAT		41
#define MEM_TYPE_FIFO_DOUBLE	42
#define MEM_TYPE_FIFO_UINT64	43
#define MEM_TYPE_FIFO_UINTx3	44
#define MEM_TYPE_FIFO_UINTx4	45
#define MEM_TYPE_FIFO_UINTx5	46


//----- MEM_TYPE_STRING -----------------------------
#define EBMMEM_STRING_SIZE 2
#define EBMMEM_STRING_APP_NAME 				0
#define EBMMEM_STRING_BOOT_NAME				1

//----- MEM_TYPE_BIT --------------------------------
#define EBMMEM_BIT_SIZE 					76
#define EBMMEM_BIT_BOOTLOADER				0
#define EBMMEM_BIT_REBOOT					1
#define EBMMEM_BIT_SUBSCRIBE_FWUPDATE		2
#define EBMMEM_BIT_SUBSCRIBE_ALL			3
#define EBMMEM_BIT_SEND_ALL_ONCE			4

#define EBMMEM_BIT_INPUT_START				10
// input 1-28  	: 10-37
#define EBMMEM_BIT_INPUT_FAULT				38
#define EBMMEM_BIT_OUTPUT_START				40
// output 1-18 	: 40-57
#define EBMMEM_BIT_FORCE_OUTPUT_START		58
// output 1-18 	: 58-75

//----- MEM_TYPE_UINT8 -------------------------------
#define EBMMEM_UINT8_SIZE 					12
#define EBMMEM_UINT8_BOOT_STATE				0
#define EBMMEM_UINT8_FWUPDATE_CMD	 		1
	#define FWUPDATE_CMD_NONE					0
	#define FWUPDATE_CMD_RECEIVE_BOOTLOADER 	1
	#define FWUPDATE_CMD_RECEIVE_APPLICATION 	2
	#define FWUPDATE_CMD_RECEIVE_FINISHED		3
	#define FWUPDATE_CMD_BURN_BOOTLOADER		4
	#define FWUPDATE_CMD_BURN_APPLICATION		5
#define EBMMEM_UINT8_FWUPDATE_RESPONSE		2
	#define FWUPDATE_RESPONSE_NONE				0
	#define FWUPDATE_RESPONSE_RECEIVING			1
	#define FWUPDATE_RESPONSE_RECEIVED_OK		2
	#define FWUPDATE_RESPONSE_BURNING			3
	#define FWUPDATE_RESPONSE_BURN_OK			4
	#define FWUPDATE_RESPONSE_ERROR_WRITE		10
	#define FWUPDATE_RESPONSE_ERROR_INTEGRITY	11
	#define FWUPDATE_RESPONSE_ERROR_FIFO		12
#define EBMMEM_UINT8_FWUPDATE_PROGRESS		3
#define EBMMEM_UINT8_CONFIG_INPUT_01		4
#define EBMMEM_UINT8_CONFIG_INPUT_02		5
#define EBMMEM_UINT8_CONFIG_INPUT_03		6
#define EBMMEM_UINT8_CONFIG_INPUT_04		7
#define EBMMEM_UINT8_CONFIG_INPUT_05		8
#define EBMMEM_UINT8_CONFIG_INPUT_06		9
#define EBMMEM_UINT8_CONFIG_INPUT_07		10
#define EBMMEM_UINT8_CONFIG_INPUT_08		11

//----- MEM_TYPE_INT8 --------------------------------
#define EBMMEM_INT8_SIZE 0

//----- MEM_TYPE_UINT16 ------------------------------
#define EBMMEM_UINT16_SIZE 3
#define EBMMEM_UINT16_FIFO_FWUPDATE_FREE	0
#define EBMMEM_UINT16_ANALOG_OUT1_GAIN		1
#define EBMMEM_UINT16_ANALOG_OUT1_OFFSET	2

//----- MEM_TYPE_INT16 -------------------------------
#define EBMMEM_INT16_SIZE 0

//----- MEM_TYPE_UINT32 --------------------------------
#define EBMMEM_UINT32_SIZE 17
#define EBMMEM_UINT32_APP_VERSION 			0
#define EBMMEM_UINT32_BOOT_VERSION 			1
#define EBMMEM_UINT32_PASSWORD	 			2
#define EBMMEM_UINT32_HW_CPU_ARTNO 			3
#define EBMMEM_UINT32_HW_CPU_VERSION 		4
#define EBMMEM_UINT32_HW_CPU_SERIALNO 		5
#define EBMMEM_UINT32_HW_CPU_MFD	 		6
#define EBMMEM_UINT32_USER_IP		 		7
#define EBMMEM_UINT32_USER_NETMASK	 		8
#define EBMMEM_UINT32_USER_GATEWAY	 		9

#define EBMMEM_UINT32_WATCHDOG_TIME 		10
#define EBMMEM_UINT32_WATCHDOG_OUTPUTS 		11
#define EBMMEM_UINT32_ENCODER_1		 		12
#define EBMMEM_UINT32_ENCODER_2 			13
#define EBMMEM_UINT32_HW_CPU_TYPE			14
#define EBMMEM_UINT32_CONFIG_UART_1			15
#define EBMMEM_UINT32_CONFIG_UART_2			16

//----- MEM_TYPE_INT ---------------------------------
#define EBMMEM_INT32_SIZE 18
#define EBMMEM_INT32_STEP1_STATUS			0
#define EBMMEM_INT32_STEP2_STATUS			1
#define EBMMEM_INT32_STEP3_STATUS			2
#define EBMMEM_INT32_STEP4_STATUS			3
#define EBMMEM_INT32_STEP5_STATUS			4
#define EBMMEM_INT32_STEP6_STATUS			5
#define EBMMEM_INT32_STEP1_CURPOS			6
#define EBMMEM_INT32_STEP2_CURPOS			7
#define EBMMEM_INT32_STEP3_CURPOS			8
#define EBMMEM_INT32_STEP4_CURPOS			9
#define EBMMEM_INT32_STEP5_CURPOS			10
#define EBMMEM_INT32_STEP6_CURPOS			11
#define EBMMEM_INT32_STEP1_CURSPEED			12
#define EBMMEM_INT32_STEP2_CURSPEED			13
#define EBMMEM_INT32_STEP3_CURSPEED			14
#define EBMMEM_INT32_STEP4_CURSPEED			15
#define EBMMEM_INT32_STEP5_CURSPEED			16
#define EBMMEM_INT32_STEP6_CURSPEED			17

//----- MEM_TYPE_FLOAT -------------------------------
#define EBMMEM_FLOAT_SIZE 7
#define EBMMEM_FLOAT_ANALOG_IN1 		0
#define EBMMEM_FLOAT_ANALOG_IN2 		1
#define EBMMEM_FLOAT_ANALOG_IN3 		2
#define EBMMEM_FLOAT_ANALOG_OUT1 		3
#define EBMMEM_FLOAT_ANALOG_OUT2 		4
#define EBMMEM_FLOAT_ANALOG_OUT3 		5
#define EBMMEM_FLOAT_ANALOG_OUT4 		6
//----- MEM_TYPE_DOUBLE -------------------------------
#define EBMMEM_DOUBLE_SIZE 0
//----- MEM_TYPE_UINT64 --------
#define EBMMEM_UINT64_SIZE 1
#define EBMMEM_UINT64_MAC_ADDRESS		0
//----- MEM_TYPE_UINTx3 --------
#define EBMMEM_UINTx3_SIZE 0
//----- MEM_TYPE_UINTx4 --------
#define EBMMEM_UINTx4_SIZE 0
//----- MEM_TYPE_UINTx5 --------
#define EBMMEM_UINTx5_SIZE 0


//-------------FIFO TYPES---------------------------------
// unused fifo types
#define EBMMEM_FIFO_STRING_SIZE	0
#define EBMMEM_FIFO_BIT_SIZE	0
#define EBMMEM_FIFO_INT8_SIZE	0
#define EBMMEM_FIFO_INT16_SIZE	0
#define EBMMEM_FIFO_UINT32_SIZE	0
#define EBMMEM_FIFO_INT32_SIZE	0
#define EBMMEM_FIFO_FLOAT_SIZE	0
#define EBMMEM_FIFO_DOUBLE_SIZE	0
#define EBMMEM_FIFO_UINT64_SIZE	0
#define EBMMEM_FIFO_UINTx3_SIZE	0
#define EBMMEM_FIFO_UINTx4_SIZE	0

//----- MEM_TYPE_FIFO_UINT8 --------------------------
#define EBMMEM_FIFO_UINT8_SIZE	5
#define EBMMEM_FIFO_UINT8_FIRMWARE		0
#define EBMMEM_FIFO_UINT8_UART1_TX		1
#define EBMMEM_FIFO_UINT8_UART1_RX		2
#define EBMMEM_FIFO_UINT8_UART2_TX		3
#define EBMMEM_FIFO_UINT8_UART2_RX		4

// ------ MEM_TYPE_FIFO_UINT16 ------------------------
#define EBMMEM_FIFO_UINT16_SIZE	2
#define EBMMEM_FIFO_UINT16_SUBSCRIBE	0
#define EBMMEM_FIFO_UINT16_SEND_MEM		1

// ------ MEM_TYPE_FIFO_UINTx5 ------------------------
#define EBMMEM_FIFO_UINTx5_SIZE	2
#define EBMMEM_FIFO_UINTx5_INPUT_INT	0
#define EBMMEM_FIFO_UINTx5_COMMAND		1

// ------ CONFIG_UART -------------
// baudrate: first 24 bits
#define CONFIG_UART_DATA_BITS_5	(0 << 24)
#define CONFIG_UART_DATA_BITS_6	(1 << 24)
#define CONFIG_UART_DATA_BITS_7	(2 << 24)
#define CONFIG_UART_DATA_BITS_8	(3 << 24)
#define CONFIG_UART_STOP_BITS_1	(0 << 26)
#define CONFIG_UART_STOP_BITS_2	(1 << 26)
#define CONFIG_UART_PARITY_NONE	(0 << 28)
#define CONFIG_UART_PARITY_EVEN	(1 << 28)
#define CONFIG_UART_PARITY_ODD	(2 << 28)

#endif /* EBMMEMDEFS_H_ */
